apiVersion: v1
kind: ConfigMap
metadata:
  name: restapi-config
  namespace: student-api
data:
  postgres_port: "5432"
  postgres_host: "postgres-svc"  
  port: "8002"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: restapi-deployment 
  namespace: student-api
  labels:
    app: restapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restapi 
  template:
    metadata:
      labels:
        app: restapi 
    spec:
      nodeSelector:
        type: application
      containers:
      - name: restapi 
        image: venkateshtangaraj/studentapi:v1.0.1
        ports:
        - containerPort: 8002
        envFrom:
        - secretRef:
            name: dev-db 
        env:
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: restapi-config
              key: postgres_port
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: restapi-config
              key: postgres_host
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: restapi-config
              key: port
      initContainers:
        - name: migration
          image: venkateshtangaraj/studentapi:v1.0.1
          env:
          - name: PYWAY_TYPE
            value: "postgres"
          - name: PYWAY_TABLE
            value: "pyway_schema_history"
          - name: PYWAY_DATABASE_MIGRATION_DIR
            value: "/app/migrations"
          - name: PYWAY_DATABASE_HOST
            valueFrom:
              configMapKeyRef:
                name: restapi-config
                key: postgres_host
          - name: PYWAY_DATABASE_PORT
            valueFrom:
              configMapKeyRef:
                name: restapi-config
                key: postgres_port
          - name: PYWAY_DATABASE_NAME
            valueFrom:
              secretKeyRef:
                name: dev-db
                key: POSTGRES_DB
          - name: PYWAY_DATABASE_USERNAME
            valueFrom:
              secretKeyRef:
                name: dev-db
                key: POSTGRES_USER
          - name: PYWAY_DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dev-db
                key: POSTGRES_PASSWORD
          
          command: ["sh", "-c"]
          args: ["pyway migrate"]
  

---
apiVersion: v1
kind: Service
metadata:
  name: restapi-service
  namespace: student-api
spec:
  type: NodePort
  selector:
    app: restapi    
  ports:
    - port: 8080        
      targetPort: 8002 
      nodePort: 30007