apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: external-secretsstores
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secrets"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-token"
          namespace: "external-secrets"
          key: "token"
