apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets

---
apiVersion: v1
kind: Namespace
metadata:
  name: student-api
---

apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: external-secretsstores
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secrets"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-token"
          namespace: "external-secrets"
          key: "token"

---
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: external-secrets
data:
  token: <token>


---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secrets
  namespace: student-api
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: external-secretsstores
    kind: ClusterSecretStore
  target:
    name: dev-db
  dataFrom:
  - extract:
      key: DBSECRETS

