apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secrets
  namespace: student-api
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: external-secretsstores
    kind: ClusterSecretStore
  target:
    name: dev-db
  dataFrom:
  - extract:
      key: DBSECRETS