# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: postgres-policy
#   namespace: student-api
# spec:
#   podSelector:
#     matchLabels:
#       app: postgres    
#   policyTypes:
#     - Ingress
#   ingress:
#     - from:
#       - podSelector:
#           matchLabels:
#             app: restapi    
#       ports:
#         - protocol: TCP
#           port: 5432   
# ---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kind-pv
  namespace: student-api
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /data/postgres-pv

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kind-pvc
  namespace: student-api
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: student-api
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      nodeSelector:
        type: database
      containers:
      - name: postgres
        image: postgres:15.3
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: dev-db 
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: kind-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: student-api
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

